safe: false
source: .
destination: ./_site
plugins_dir: ./_plugin
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', '.sass-cache']

gems:
  - jekyll-compass

url: https://ice-ar.named-data.net
baseurl: 

# Configuration for site
title: ICN-Enabled Secure Edge Networking with Augmented Reality (ICE-AR)
logo_title: ICE-AR Project
author: ICE-AR Project Team
email:
logo: assets/img/logo.png

navbar_list:
- name: Home
  link: /
- name: Meetings
  link: meetings.html
- name: Codebases
  link: codebase.html
- name: Publications
  link: pub.html
- name: Project Team
  link: team.html

# google_analytics:
#    account: UA-XXXXX-X

# jekyll-scholar configurations
scholar:
  style: apa
  locale: en
  bibliography_template: pub

  sort_by: year,month
  order: descending

  source: ./_publications
  bibliography:
    - pub.bib
    - background.bib
  details_dir: ./publications/details
  details_layout: details.html
  #query: "@*[public!=no]"
